language: python
python:
  - "2.7"
branches:
  only:
    - master
install:
  - "pip install -r requirements.txt"
before_script:
  - psql -c 'create database insightful;' -U postgres
  - python manage.py syncdb --noinput
script:
  - python manage.py test